#!/bin/bash

echo "=== 百度翻译API修复验证 ==="
echo "修复内容："
echo "✅ 修复签名格式：移除.toUpperCase()，使用32位小写MD5"
echo "✅ 修复签名字符串：appid+q+salt+密钥"
echo "✅ 修复请求方式：POST + application/x-www-form-urlencoded"
echo "✅ 修复URL编码：发送前对q做encodeURIComponent"
echo ""

echo "测试步骤："
echo "1. 在Deno环境中设置环境变量："
echo "   export BAIDU_TRANSLATE_APP_ID=您的appid"
echo "   export BAIDU_TRANSLATE_SECRET_KEY=您的密钥"
echo ""
echo "2. 启动翻译服务："
echo "   cd nanobanana-modified"
echo "   deno run --allow-net --allow-env main.ts"
echo ""
echo "3. 访问 http://localhost:8000 测试翻译功能"
echo ""

echo "预期结果："
echo "✅ 不再出现54001签名错误"
echo "✅ 成功返回翻译结果"
echo "✅ 控制台显示正确的签名字符串和MD5签名"
echo ""

echo "如果仍有问题，请提供："
echo "- 翻译测试结果"
echo "- 控制台错误日志"
echo "- 签名生成信息"